- README.md
- bubuku/daemon.py
- bubuku/features/rebalance.py
- tests/test_daemon.py
- tests/test_rebalance.py
> Different improvements regarding rebalance prcess

- bubuku/controller.py
- bubuku/features/rebalance.py
- bubuku/features/restart_if_dead.py
- bubuku/features/restart_on_zk_change.py
- tests/test_check_time_period.py
@antban @adyach @v1ctor @rcillo please review
> fixes #18; added configurable period for check execution;

- bubuku/daemon.py
@antban @rcillo @adyach @v1ctor please review
> Fix daemon

- bubuku/controller.py
- bubuku/features/rebalance.py
- bubuku/features/restart_if_dead.py
- bubuku/features/swap_partitions.py
And do not try to start dead broker several times
> Pause rebalance on start/stop/restart instead of stopping it completely

- README.md
- bubuku/cli.py
- bubuku/daemon.py
- bubuku/features/remote_exec.py
- bubuku/features/restart_on_zk_change.py
- bubuku/zookeeper/__init__.py
- requirements.txt
- setup.py
- tests/test_restart.py
- tests/test_zookeeper.py
Make possibility to trigger rebalance and restart by calling special methods of bubuku.
> #39 Add remote commands processing

- bubuku/zookeeper/__init__.py
@antban @rcillo @v1ctor @adyach please review
> #17 hotfix

- bubuku/cli.py
- bubuku/features/migrate.py
- bubuku/features/remote_exec.py
- tests/test_migrate.py
> Implement functionality for migration

- Dockerfile
- bubuku/features/terminate.py
> Graceful terminate should work even after several restarts

- bubuku/features/rebalance/broker.py
- bubuku/features/rebalance/change.py
- tests/test_rebalance.py
> Fix rebalancing bug with no partitions left for leadership rebalance

- .zappr.yaml
https://techjira.zalando.net/browse/ARUHA-655
> ARUHA-655: add zappr for compliance

- bubuku/cli.py
> Fix migrate call

- .zappr.yaml
https://techjira.zalando.net/browse/ARUHA-655?focusedCommentId=1730631&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1730631
> aruha-655 require 2 approvals

- bubuku/broker.py
- bubuku/features/restart_if_dead.py
- bubuku/features/restart_on_zk_change.py
- bubuku/zookeeper/__init__.py
- tests/test_restart.py
> ARUHA-717 Wait for broker to be part of isr list before finishing restart

- .zappr.yaml
This project is currently non compliant, even though we followed all the
instructions on how to properly setup zappr.
I have been instructed by the team responsible that I should remove
everything else but the 2 necessary lines with X-Zalando-Team and
X-Zalando-Type.
> aruha-747 fix zappr violations

- .zappr.yaml
These changes have been tested in Nakadi repository and should also be applied to this repo.
> aruha-747 fix violations

- instance_control/readme.md
> aruha-729: improved docs

- instance_control/aws/security_group.py
> aruha-729: removed port

- bubuku/broker.py
- bubuku/features/restart_on_zk_change.py
- tests/test_restart.py
> aruha-842: removed ISR check

- .github/PULL_REQUEST_TEMPLATE.md
[ARUHA-940: Create PR template](https://techjira.zalando.net/browse/ARUHA-940)
We are introducing PR templates to help developers provide the basic information when opening a new PR with a contribution. I'm using the template itself to check if it looks good.
Some of the info in the template might not be required for all PRs. So you can just delete it. But make it consciously.
These should highlight any db migrations, feature toggles, etc.
> aruha-940 add Pull Request template

- instance_control/aws/__init__.py
- instance_control/aws/ec2_node.py
- instance_control/aws/iam.py
- instance_control/aws/metric.py
- instance_control/aws/security_group.py
- instance_control/aws/subnet.py
- instance_control/aws/taupage.py
- instance_control/bubuku-1.json
- instance_control/bubuku_cluster.py
- instance_control/command/attach.py
- instance_control/command/create.py
- instance_control/command/get.py
- instance_control/command/terminate.py
- instance_control/command/upgrade.py
- instance_control/node.py
- instance_control/volume.py
- requirements.txt
[ARUHA-1099: (reached max retries: 4)]
Use exponential backoff with different max retries for AWS communication
There are no deployment notes, cause changed part is related only to aws deployment scripts, and not to service.
> Aruha 1099 reached max retries: 4

- instance_control/aws/ec2_node.py
- instance_control/command/upgrade.py
> Expose StackName tag to AWS

- instance_control/aws/taupage.py
- instance_control/bubuku-1.json
- instance_control/readme.md
ARUHA-1389:     Migrate Scalyr to EU
This PR adds the scalyr_region property to taupage, if specified in the configuration file
> ARUHA-1389 add scalyr region to taupage

- instance_control/readme.md
Simple wording fix in the documentation.
> Fix wording

- instance_control/aws/iam.py
ARUHA-1613 Support kms_key_id in configuration, so policy for accessing the key will be automatically generated
> ARUHA-1613 Support kms key id

- bubuku/cli.py
- bubuku/features/metric_collector.py
- bubuku/health.py
[ARUHA-2080](https://jira.zalando.net/browse/ARUHA-2080) - Collect Kafka cluster metrics in Bubuku 
Collect bad things metrics and expose via api
> Collect bad-things metrics and expose via api and cli

- bubuku/features/metric_collector.py
[ARUHA-2103: Fix metric endpoint to indicate missing metrics](https://jira.zalando.net/browse/ARUHA-2103)
Previously, metric endpoint doesn't state if it was able to fetch all metrics for all brokers.
> Indicate if all required metrics were fetched

- bubuku/cli.py
I must have missed the change during merge. This fixes it.
> Fix function name when fetching config

- README.md
- bubuku/config.py
- bubuku/env_provider.py
- instance_control/aws/taupage.py
Allow to use static ips for zookeeper stack.
> ARUHA-2181 Allow to use static ip list of zookeeper stack

- bubuku/cli.py
- bubuku/zookeeper/__init__.py
Needed this to fix problem of 1 mb in kafka.
> Create command that fixes preferred replica imbalance

- bubuku/features/rolling_restart.py
> ARUHA-2434: key for key. region for region

- .travis.yml
- Dockerfile
- delivery.yaml
- docker/download_kafka.sh
- docker/log4j.properties
- instance_control/aws/taupage.py
Aruha 2607 - rework docker image creation
> Aruha 2607 - rework docker image creation

- instance_control/aws/taupage.py
- instance_control/bubuku-1.json
Allow setting of sysctl options in taupage config
> set sysctl options from config

- docker/server.properties
This is the last step in the upgrade.
> Production deployment of log.message.format.version 2.6.0

- docker/server.properties
ARUHA-3122 Increase kafka thread pools size
> ARUHA-3122 Increase kafka thread pools size

- Dockerfile
Prepare build of bubuku with 2.7.0 version
> Build 2.7.0 version without settings changes

- docker/server.properties
Update inter.broker.protocol.version to 2.7 (intermediate for migration)
> Update inter.broker.protocol.version to 2.7

- docker/server.properties
Update log.message.format version to 2.7
> Update log.message.format version to 2.7

- Dockerfile
New upstream release.
Internal ticket: #759
These should highlight any db migrations, feature toggles, etc.
> Upgrade Kafka to 2.7.1

- bubuku/daemon.py
- bubuku/features/rebalance/__init__.py
- bubuku/features/remote_exec.py
- bubuku/features/restart_if_dead.py
- bubuku/features/restart_on_zk_change.py
- bubuku/features/rolling_restart.py
- bubuku/features/terminate.py
Always try to start the broker even in case of a rolling restart.
Internal ticket number: 706
> Remove explicit start from the rolling restart

- bubuku/cli.py
This enables capturing undecorated output of commands to a file.
> Logo should be printed to stderr

- bubuku/cli.py
- tests/test_cli.py
We need to be able to dump a single file as the input for Kafka scripts.
Internal ticket: 797
> Dump preferred partition assignment in one piece

- Dockerfile
Staying on top of the change.
Internal ticket: 858
> Upgrade OpenJDK to 11

- bubuku/cli.py
- bubuku/utils.py
- bubuku/zookeeper/__init__.py
> Add throttling commands

- Dockerfile
- delivery.yaml
Uses approved zalando image as a base, but makes a small hack use different base image
> Use corretto JDK 11 for kafka

- Dockerfile
- delivery.yaml
This reverts commit 8ef6ba1f8e44a0141e6e95c6d9d09bb6cb5ca5b4, reversing
changes made to 6560ee1026d3e81b9403313a53be9b3d1d37e0a9.
> Revert "Merge pull request #192 from zalando-nakadi/correto"

- bubuku/aws/ec2_node_launcher.py
Fight eventual consistency issues in AWS API.
> Retry create_tags call

- Dockerfile
Part of Internal ticket : 1104
Update kafka binary version to 3.1.1
> use kafka binary version 3.1.1

- docker/server.properties
Part of internal ticket: 1104
Updating interbroker protocol version to 3.1
> Update interbroker protocol version to 3.1

- docker/server.properties
Reverts zalando-nakadi/bubuku#198, to be merged back after #199
> Revert "Update interbroker protocol version to 3.1"

- docker/server.properties
Reverts zalando-nakadi/bubuku#200
> Revert "Revert "Update interbroker protocol version to 3.1""

- docker/server.properties
Update log.message.format.version to 3.1
> Update log.message.format.version to 3.1

- bubuku/daemon.py
- tests/test_daemon.py
- Add advertised.listeners property and set it to broker ip
- listeners property  is now set to localhost as well as broker ip
> Add advertised.listeners separately

- bubuku/daemon.py
- docker/server.properties
- tests/test_daemon.py
Bind listener property to listen at all hosts
> Bind listener property to listen at all hosts

- docker/log4j.properties
> Reduce Kafka log level

- Dockerfile
- delivery.yaml
1. Build multi-arch and push it to the new container registry.
2. Re-publish arch-specific images to OSS PierOne.
> Use proper allowed base docker image
