zalando-nakadi/bubuku

bubuku/amazon.py, bubuku/daemon.py, bubuku/zookeeper/__init__.py, bubuku/zookeeper/exhibior.py, tests/test_zookeeper.py
The problem is that sometimes exhibitor notifies about changes in zookeeper list.
But sometimes it's not the real change - It's just problem in network connection and so on.
In this pr check for changes is performed every 30 seconds, but real update will be made only if exhibitor connection is stable for more than 180 seconds (numbers are taken from logs of exhibitor/bubuku).
=> Implement slow refresh of exhibitors

bubuku/features/rebalance.py, bubuku/zookeeper/__init__.py, tests/test_rebalance.py
Rebalance operation can not be completed for partitions, that do not have any in sync replica online. 
That means, that no one broker can provide data for these partitions. Therefore, it's better not even try to rebalance these partitions
=> Do not rebalance partitions that do not have in-sync replicas

README.md, bubuku/broker.py, bubuku/config.py, bubuku/daemon.py, tests/test_broker.py, tests/test_config.py, tests/test_startup_timeout.py
=> Make kafka startup timeout configurable

Dockerfile, README.md, bubuku/env_provider.py, bubuku/zookeeper/__init__.py, bubuku/zookeeper/exhibitor.py, setup.py, tests/test_exhibitor.py, tests/test_zookeeper.py
Or at least allow to recover after it. Fixes #59
=> Handle network errors in proper way

bubuku/cli.py, bubuku/communicate.py, bubuku/controller.py, bubuku/health.py, bubuku/zookeeper/__init__.py, tests/test_controller.py
=> Ability to list and cancel running (and queued) actions of bubuku

instance_control/aws/taupage.py, instance_control/bubuku-1.json
[ARUHA-1114: SCM_URL_NOT_MATCH_WITH_KIO for bubuku](https://techjira.zalando.net/browse/ARUHA-1114)
When deploying a new bubuku stack, we don't want to necessarily have to
setup a new application in Kio. So we are decoupling application id from
stack name.
Don't forget to always update all repositories, since this PR depends on configurations changed in the private repo.
=> aruha-1114 decouple application id from stack name

instance_control/bubuku_cluster.py
[ARUHA-1150: Force option for bubuku upgrade script](https://techjira.zalando.net/browse/ARUHA-1150)
=> aruha-1150: changed to flag

instance_control/command/terminate.py, instance_control/command/upgrade.py, instance_control/piu.py
If the user executing the script has a default region different from the
one specified by the cluster config, the script is aborted.
This PR makes sure that the region used in piu is the same as the one
configured in the cluster parameters.
=> aruha-1456 avoid region inconsistency

instance_control/aws/security_group.py
https://jira.zalando.net/browse/ARUHA-2397
In order to migrate bubuku we need to create a new security group in the new VPC. Since the old code fetched the old security group it had problems when launching a new bubuku instance. This is fixed in the PR. 
It is running on staging.
=> added additional filter of vpc id to migrate

docker/server.properties
As part of the global project for customer data deletion, log
compaction has a new maximum lag of 14 days, after which compaction
happens.
This change has already been applied dynamically to our production and
test cluster, but in the case a new cluster gets deployed in the
future, in order to avoid a "regression" from sneaking in, we better
build bubuku with this property by default, that way our current
solution becomes future proof.
=> Make sure new cluster's max compaction lag is 14 days

Dockerfile, delivery.yaml
CDP is logging
```
+ pip3 install -r requirements.txt
pyenv: version `3.6.9' is not installed (set by PYENV_VERSION environment variable)
Step finished unsuccessfully.
Step 'Run tests' finished unsuccessfully.
```
Probably the base image being openjdk we need to first install python
tooling before using it. I don't have a lot of experience with python so I'm not sure. Maybe it's just missing some env variable, so I'm trying out.
=> Fix CDP error with pyenv version

Dockerfile
When bubuku process is booting it overwrites the broker id in server
properties (or at least open this file with write permission).
The lack of such permission resulted in:
```
ERROR:bubuku.features.restart_on_zk:Failed to start kafka process against 10.154.206.111:2181,10.154.192.139:2181,10.154.215.44:2181/staging-fra-2
Traceback (most recent call last):
File "/bubuku/bubuku/features/restart_on_zk_change.py", line 38, in run
self.broker.start_kafka_process(zk_conn_str)
File "/bubuku/bubuku/broker.py", line 133, in start_kafka_process
self.kafka_properties.dump()
File "/bubuku/bubuku/config.py", line 47, in dump
with open(self.settings_file, mode='w') as f:
PermissionError: [Errno 13] Permission denied:
'/opt/kafka/config/server.properties'
```
I'm not sure why it works locally with …
=> Grant write permissions to files that need to be changed

bubuku/zookeeper/__init__.py, requirements.txt, tests/test_zookeeper.py
Upgraded libraries to the latest version.
The renaming of the `async` var name was required because it is a python keyword nowadays.
=> libraries upgrade

Dockerfile
This upgrade addresses major issues that impact Nakadi SQL (on the
client side) as well as performance issues on the broker side (large
number of partitions per broker are now less taxing on cpu).
You can read more about the changes in this blog post https://blogs.apache.org/kafka/entry/what-s-new-in-apache3
=> Upgrade Kafka to version 2.6.0 with Scala 2.13

docker/server.properties
This changes the inter broker protocol to the latest version. Once
this is rolled out, there is no rolling back to the previous Kafka
version. At least not that the documentation recommends.
=> Kafka ugprade to 2.6.0 phase 2 of 3

docker/server.properties
Since the previous release where we modified the
inter.broker.protocol.version to version 2.6.0 we noticed an increase
in CPU usage. We suspect it could be due to conversions so we are
going to try to deploy Kafka with message format 2.6 to see if we less
conversions the CPU usage goes down.
Since most messages come from Nakadi with version 2.6 client, this
should reduce amount of conversions done.
=> Upgrade Kafka 2.6.0 part 3: log.message.format

bubuku/features/rolling_restart.py, docker/server.properties
Start restart from a specific broker
When performing a rolling restart, if broker A is restarting broker B
and for some reason an exception is thrown, this exception might cause
the rolling restart process to be interrupted.
This just happened on production leaving our cluster with 1 less
instance.
In order to be able to resume the rolling restart exactly where it
stopped, without having to restart everything from the beginning, I
changed this 1 line of code.
The plan is to upgrade one broker and trigger the rolling restart from
there. Then, this will cause the rolling restart to go from there
on. It will eventually restart brokers that were already restarted in a
previous run of the rolling restart but at least we are now able to
run rolling restart from a specific point and be sure it …
=> Enable rolling restart resuming

docker/server.properties
This is a continuation of
https://github.com/zalando-nakadi/bubuku/pull/158 which was built for
staging validation. Now I'm setting log.message.format to 2.4 to
continue production deployment.
=> Make special build for production deployment

bubuku/cli.py
We learned from experience that rolling restarts are less disruptive
when performed slowly over time. This gives consumers enough time to
breath (rebuild state or properly fetch up-to-date metadata and
dispatch potentially accumulated backlog) in between restarts.
We are making the default 10 minutes so that the next person to
perform a rolling restart doesn't have to find out the hard way that
speedy rolling restarts may cause incidents.
=> Change default cooldown to 10 minutes

bubuku/broker.py, bubuku/zookeeper/__init__.py, tests/test_broker.py, tests/test_zookeeper.py
[ARUHA-3130: Bubuku may hang up on start](https://jira.zalando.net/browse/ARUHA-3130)
Bubuku may hang up on start for new topics being under creation. For example:
```
WARNING:bubuku.broker:Leadership is not transferred for 769c2845-4aee-4b38-8b80-087cc08817e4 2 ({"controller_epoch": 61, "leader": -1, "version": 1, "leader_epoch": 110, "isr": [67123066]}, brokers: ['67123027', '67123028', '67123033', '67123034', '67123035', '67123036', '67123037', '67123038', '67123039', '67123040', '67123041', '67123044', '67123046', '67123047', '67123048', '67123049', '67123050', '67123051', '67123052', '67123053', '67123055', '67123056', '67123057', '67123058', '67123059', '67123060', '67123061', '67123062', '67123063', '67123064', '67123065', '67123066', '67123427'])
```
In this pull request, I change …
=> Wait for leadership finish and exclude new topics

Dockerfile
Use different base image (more recent)
=> Use registry.opensource.zalan.do/library/openjdk-8:8-20210107 as base image

bubuku/cli.py
By default rolling-restart is not showing wich instance type will be used.
This leads to a situation when users do not know what they are execution.
This PR enforces users to specify instance type and removes incorrect
default value (that is hidden, btw)
=> Fix instance-type option in rolling-restart bubuku-cli command

bubuku/broker.py, bubuku/env_provider.py, bubuku/id_extractor.py, delivery.yaml, tests/test_broker_id_generator.py, tests/test_check_time_period.py, tests/test_daemon.py
Update python version for running tests on build machine, fix test warnings
=> Misc updates

docker/server.properties
In case if clients are asking to consume from follower, they are still forced to consume from leader. 
In this PR the rack selector is modified to comply with client wishes - consumer from the same rack. 
`broker.rack` value is set by AWS environment provider. In case if clients do want to continue consumption from the leader, they have to avoid setting `client.rack`.
=> Use rack-aware replica selector for consumption

bubuku/features/remote_exec.py, bubuku/features/restart_on_zk_change.py, bubuku/features/rolling_restart.py
Follow up on #173
Also, remove `StartBrokerChange`: it is not used anywhere else.
=> Don't prevent start of broker under rolling_restart

bubuku/controller.py
Be prepared to modification of change list while iterating over it.
CompleteStopChange derives StopChange, and leads to problems iterating the `self.changes` in controller
Iteration over copy of dict solves the issue
=> Be prepared to modification of change list while iterating over it

bubuku/daemon.py, docker/log4j.properties
It's harder to debug issues without the timestamps.
The format matches the one we currently use for the Kafka server.
Internal ticket: 789
=> Add timestamp to log messages from bubuku

bubuku/controller.py, bubuku/features/rolling_restart.py
Apply 10 seconds timeout for `RollingRestartChange` as the default 0.5 seconds
is way too often for the operation of this change.
Internal ticket: 789
=> Make timeout before next run of a change configurable

bubuku/controller.py
1. Changes is not a list, but a mapping from name to list of `Change` objects.
2. Change with a long timeout should not postpone run of scheduled checks.
3. A newly added change has to be executed without delay caused by other changes.
Internal ticket: 789
=> Fix calculation of timeout before next change run

Dockerfile
It didn't work with JDK 8 either, as JVM didn't have permissions to create the
logs directory, but it became a fatal error in JDK 11.
JVM flags like `UseGCLogFileRotation` are not supported anymore and Kafka
startup script sets its own values anyway.
Follow up on: #182
=> Fix GC log parameters for JDK 11

Dockerfile, delivery.yaml
Right now the base image for bubuku is not supporting multiarch, hence it makes it impossible to run on arm64 architectures.
This PR allows to make 2 different images based on 2 different base images, that are allowing to run bubuku+kafka on 2 different platrorms (amd64 and arm64)
=> Build 2 different images for different platforms

bubuku/aws/cluster_config.py, bubuku/aws/ec2_node_launcher.py, bubuku/aws/ip_address_allocator.py, bubuku/cli.py, bubuku/features/remote_exec.py, bubuku/features/rolling_restart.py
Right now during rolling-restart bubuku is trying to find some ami according to some filter that is hard coded in the bubuku code. 
This PR is making it different - the ami that is used on the instance will be used on all the other instances. 
The upgrade procedure is the following: 
1. upgrade ami on one of the instances.
2. run the rolling restart from that instance.
=> Use the same ami as the instance that does the restart.

bubuku/aws/cluster_config.py
With the new version of pyaml (6), Loader arg became mandatory.
=> Fix yaml loader

bubuku/features/restart_if_dead.py
If bubuku realizes that the broker is actually recovered, it should reset the last failed check because a restart change might not be necessary on events when it recovers.
ARUHA-175
=> Reset the failed check timestamp

Dockerfile
Corretto 17 JDK for kafka
Try to use version 17 for kafka in hope of performance optimizations
=> Corretto 17 JDK for kafka

bubuku/controller.py, bubuku/daemon.py, bubuku/env_provider.py, docker/server.properties, requirements.txt, tests/test_config.py, tests/test_daemon.py, tests/test_restart_if_dead.py
After [kafka 3.0 release](https://kafka.apache.org/documentation/#upgrade_300_notable) there were some properties removed: 
`advertised.host.name, advertised.port, port`. 
The new way of managing these properties is to use `listeners` and `advertized.listeners` configuration.
=> Use listeners kafka property instead of advertised.host.name and port properties
